version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb+srv://laluprasathdevin:laluprasath02@cluster0.vqykbru.mongodb.net/develop?retryWrites=true&w=majority&appName=Cluster0
